"""BigAlpha 2026 factor research utilities."""

from .feature_contracts import FEATURE_CONTRACTS
from .research_policy import (
    CANDIDATE_POOL,
    FORMAL_EVALUATION_POLICY,
    HF_OB_ACTIVATED_OPTIONAL_MONTHS,
    HF_OB_MANDATORY_MONTHS,
    HF_OB_MAX_OPTIONAL_MONTHS,
    HF_OB_OPTIONAL_MONTH_POOL,
)

__all__ = [
    "CANDIDATE_POOL",
    "FEATURE_CONTRACTS",
    "FORMAL_EVALUATION_POLICY",
    "HF_OB_ACTIVATED_OPTIONAL_MONTHS",
    "HF_OB_MANDATORY_MONTHS",
    "HF_OB_MAX_OPTIONAL_MONTHS",
    "HF_OB_OPTIONAL_MONTH_POOL",
]
